apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-chaos
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  duration: '600s'
  selector:
    namespaces:
      - train-ticket