apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress
  namespace: chaos-testing
spec:
  mode: one
  duration: '600s'
  stressors:
    memory:
      workers: 3
      size: '512MB'
  selector:
    namespaces:
      - train-ticket