apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: tt-chaos
  namespace: train-ticket
spec:
  entry: entry
  schedule:
    cron: "0,15,30,45 * * * *"
  templates:
    - name: entry
      templateType: Serial
      deadline: 4h
      children:
        - tt-chaos
    - name: network-chaos
      templateType: NetworkChaos
      deadline: 600s
      networkChaos:
        selector:
          namespaces:
            - train-ticket
        mode: one
        action: bandwidth
        bandwidth:
          rate: 2mbps
          limit: 2
          buffer: 2
        direction: to
    - name: pod-chaos
      templateType: PodChaos
      deadline: 600s
      podChaos:
        selector:
          namespaces:
            - train-ticket
        mode: one
        action: pod-kill
    - name: cpu-chaos
      templateType: StressChaos
      deadline: 600s
      stressChaos:
        selector:
          namespaces:
            - train-ticket
        mode: one
        stressors:
          cpu:
            workers: 3
            load: 70
    - name: memory-stress
      templateType: StressChaos
      deadline: 600s
      stressChaos:
        selector:
          namespaces:
            - train-ticket
        mode: one
        stressors:
          memory:
            workers: 3
            size: 512MB
    - name: tt-chaos
      templateType: Serial
      deadline: 4h
      children:
        - network-chaos
        - pod-chaos
        - cpu-chaos
        - memory-stress
