apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: tt-chaos
  namespace: train-ticket
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 4h
      children:
        - tt-chaos
    - name: network-chaos
      templateType: Schedule
      deadline: 600s
      type: NetworkChaos
      networkChaos:
        selector:
          namespaces:
            - train-ticket
        mode: all
        action: bandwidth
        bandwidth:
          rate: 2mbps
          limit: 2
          buffer: 2
        direction: to

    - name: pod-chaos
      templateType: Schedule
      deadline: 600s
      type: PodChaos    
      podChaos:
        selector:
          namespaces:
            - train-ticket
        mode: one
        action: pod-kill

    - name: cpu-chaos
      templateType: Schedule
      deadline: 600s
      type: StressChaos
      stressChaos:
        selector:
          namespaces:
            - train-ticket
        mode: one
        stressors:
          cpu:
            workers: 3
            load: 70

    - name: memory-stress
      templateType: Schedule
      deadline: 600s
      type: StressChaos
      stressChaos:
        selector:
          namespaces:
            - train-ticket
        mode: one
        stressors:
          memory:
            workers: 3
            size: 512MB

            
    - name: tt-chaos
      templateType: Serial
      deadline: 4h
      children:
        - network-chaos
        - pod-chaos
        - cpu-chaos
        - memory-stress
